### ISSUE TITLE
REST-APIデプロイ環境構築

### ISSUE THREAD

**Issue by shu0603n** [shu0603n/MUI_APP#2]
GitHub Actionsを使用して、mainブランチにプッシュしたタイミングでFLASKプロジェクトをxserverにデプロイするワークフローを作成するためのステップを示します。以下は、基本的なワークフローの設定例です：

1. リポジトリのルートに、`.github/workflows`というディレクトリを作成します。

2. そのディレクトリ内に、デプロイ用のワークフローファイル（例：`deploy.yml`）を作成します。

3. `deploy.yml`ファイル内に以下の内容を追加します：

```yaml
name: Deploy to xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Pythonのバージョンを指定します

      - name: Install dependencies
        run: pip install -r requirements.txt  # requirements.txtに依存ライブラリを記述します

      - name: Deploy to xserver
        run: |
          # デプロイコマンドを実行します。以下は一般的な例です。実際のコマンドに置き換えてください。
          ssh user@xserver-host "cd /path/to/project && git pull origin main && systemctl restart your-app"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH鍵をGitHub Secretsから取得します

```

このワークフローは、mainブランチにプッシュされた際にトリガーされ、GitHub Actionsが実行されます。コードをチェックアウトし、必要なPython環境をセットアップし、依存関係をインストールします。そして、SSH経由でxserverにアクセスしてプロジェクトをデプロイします。

重要な点：
- `SSH_PRIVATE_KEY`はGitHub Secretsから取得する必要があります。GitHubリポジトリの設定からSSH秘密鍵を設定して、`secrets.SSH_PRIVATE_KEY`としてアクセスできるようにしてください。
- デプロイコマンドは、実際のプロジェクト構成に合わせて適切に変更してください。
- セキュリティに注意し、SSHキーを適切に管理してください。

これで、mainブランチへのプッシュがトリガーとして設定されたGitHub Actionsワークフローが、FLASKプロジェクトをxserverにデプロイする準備が整いました。
